# -*- coding: utf-8 -*-
"""DivorceDataset.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fYYrLf0D7JUOguJ-g73WbQa4YNhaejAK
"""

import pandas as pd
from sklearn import preprocessing
from scipy.io import arff

# Load du lieu
df = pd.read_csv('https://raw.githubusercontent.com/CanhHo1004/dataset/main/divorce/divorce.csv', ';')
df

# Kiem tra gia tri null
total =  df.isnull().sum()
# print(total)

X = df.drop('Class', axis=1)
y = df['Class']

from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
from sklearn.tree import DecisionTreeClassifier

def score_dt(X, y, fold):
  kf = KFold(n_splits= fold)
  total = 0
  for train_index, test_index in kf.split(X):
    X_train, X_test = X.iloc[train_index, ], X.iloc[test_index, ]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]
    model = DecisionTreeClassifier()
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    total += accuracy_score(y_test, y_pred)
  return total/fold

test = score_dt(X, y, 15) # < 0.95 tai k-Fold = 15
print(test)